// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview Generates a daily affirmation.
 *
 * - generateDailyAffirmation - A function that generates a daily affirmation.
 * - GenerateDailyAffirmationInput - The input type for the generateDailyAffirmation function (currently empty).
 * - GenerateDailyAffirmationOutput - The return type for the generateDailyAffirmation function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateDailyAffirmationInputSchema = z.object({});
export type GenerateDailyAffirmationInput = z.infer<typeof GenerateDailyAffirmationInputSchema>;

const GenerateDailyAffirmationOutputSchema = z.object({
  affirmation: z.string().describe('A short, positive daily affirmation.'),
});
export type GenerateDailyAffirmationOutput = z.infer<typeof GenerateDailyAffirmationOutputSchema>;

export async function generateDailyAffirmation(
  input: GenerateDailyAffirmationInput
): Promise<GenerateDailyAffirmationOutput> {
  return generateDailyAffirmationFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateDailyAffirmationPrompt',
  input: {schema: GenerateDailyAffirmationInputSchema},
  output: {schema: GenerateDailyAffirmationOutputSchema},
  prompt: `You are a positivity expert. Generate a short, positive, and encouraging affirmation to start the day. Focus on themes of self-love, resilience, and achieving goals.`,
});

const generateDailyAffirmationFlow = ai.defineFlow(
  {
    name: 'generateDailyAffirmationFlow',
    inputSchema: GenerateDailyAffirmationInputSchema,
    outputSchema: GenerateDailyAffirmationOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
